---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tinyauth
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: TinyAuth
    gethomepage.dev/href: "https://tinyauth.kube.dev.cturner.xyz"
    gethomepage.dev/group: Access
    gethomepage.dev/icon: sh-tinyauth
    gethomepage.dev/namespace: tinyauth
    gethomepage.dev/app: tinyauth
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tinyauth.kube.dev.cturner.xyz`)
      kind: Rule
      services:
        - name: tinyauth
          port: 3000
  tls: {}
