---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
spec:
  project: default

  source:
    chart: authentik
    repoURL: https://charts.goauthentik.io
    targetRevision: 2025.8.4
    helm:
      releaseName: authentik
      valuesObject:
        authentik:
          secret_key: file:///secrets/secret-key/password
          postgresql:
            user: authentik
            password: file:///secrets/postgres-creds/password
        server:
          ingress:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
              gethomepage.dev/enabled: "true"
              gethomepage.dev/name: Authentik
              gethomepage.dev/href: "https://auth.kube.dev.cturner.xyz:8443"
              gethomepage.dev/group: Access
              gethomepage.dev/icon: sh-authentik
              gethomepage.dev/namespace: authentik
              gethomepage.dev/app: authentik
            hosts:
              - auth.kube.dev.cturner.xyz
          volumes:
            - name: postgres-creds
              secret:
                secretName: authentik-postgres-credentials
            - name: secret-key
              secret:
                secretName: authentik-secret-key
          volumeMounts:
            - name: postgres-creds
              mountPath: /secrets/postgres-creds
              readOnly: true
            - name: secret-key
              mountPath: /secrets/secret-key
              readOnly: true
        worker:
          volumes:
            - name: postgres-creds
              secret:
                secretName: authentik-postgres-credentials
            - name: secret-key
              secret:
                secretName: authentik-secret-key
          volumeMounts:
            - name: postgres-creds
              mountPath: /secrets/postgres-creds
              readOnly: true
            - name: secret-key
              mountPath: /secrets/secret-key
              readOnly: true
        postgresql:
          enabled: true
          auth:
            enablePostgresUser: false
            username: authentik
            existingSecret: authentik-postgres-credentials
        redis:
          enabled: true
        additionalObjects:
          # External Secrets
          - apiVersion: generators.external-secrets.io/v1alpha1
            kind: Password
            metadata:
              name: authentik-generator
            spec:
              length: 60
              encoding: base64
              allowRepeat: true
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: authentik-postgres-credentials
            spec:
              refreshPolicy: OnChange
              dataFrom:
                - sourceRef:
                    generatorRef:
                      apiVersion: generators.external-secrets.io/v1alpha1
                      kind: Password
                      name: authentik-generator
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: authentik-secret-key
            spec:
              refreshPolicy: OnChange
              dataFrom:
                - sourceRef:
                    generatorRef:
                      apiVersion: generators.external-secrets.io/v1alpha1
                      kind: Password
                      name: authentik-generator
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: authentik-api-token
              labels:
                # Needed to allow webhook to use this secret
                external-secrets.io/type: webhook
            spec:
              refreshPolicy: OnChange
              secretStoreRef:
                name: op-secret-store
                kind: ClusterSecretStore
              data:
                - secretKey: token
                  remoteRef:
                    key: "Authentik Admin API Token/credential"
          - apiVersion: external-secrets.io/v1
            kind: ClusterSecretStore
            metadata:
              name: authentik-oauth-store
            spec:
              provider:
                webhook:
                  url: "http://authentik-server.authentik.svc/api/v3/providers/oauth2/?name={{ `{{ .remoteRef.key }}` }}"
                  headers:
                    Content-Type: application/json
                    Authorization: "Bearer {{ `{{ .auth.token }}` }}"
                  result:
                    jsonPath: "$.results[0]"
                  secrets:
                    - name: auth
                      secretRef:
                        name: authentik-api-token
                        namespace: authentik
  destination:
    name: in-cluster
    namespace: authentik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
