---
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yml

secretGenerator:
  - name: op-api-token
    namespace: external-secrets
    envs:
      - env/op-api-token.env
